name: flutter build --release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    name: Release build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: apk --target-platform android-arm64 --split-per-abi
            file: app-arm64-v8a-release.apk
            directory: ./build/app/outputs/flutter-apk
          - os: ubuntu-latest
            target: linux
            file: linux-x64.zip
            directory: ./build/linux/x64/release/bundle/
          - os: windows-latest
            target: windows
            file: windows.zip
            directory: ./build/windows/runner/Release/
          - os: macos-latest
            target: macos
            file: gptool.app.zip
            directory: ./build/macos/Build/Products/Release/gptool.app
          - os: macos-latest
            target: ios --release --no-codesign
            file: Runner.app.zip
            directory: ./build/ios/iphoneos/Runner.app
    steps:
      - if: ${{ startsWith(matrix.target, 'windows') }}
        run: git config --system core.longpaths true
      - uses: actions/checkout@v3
      - if: ${{ startsWith(matrix.target, 'apk') }}
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - if: ${{ matrix.target == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
      - run: flutter build ${{ matrix.target }}
      - if: ${{ matrix.directory }}
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: ${{ matrix.file }}
          directory: ${{ matrix.directory }}
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.directory }}/${{ matrix.file }}
          generate_release_notes: true
          draft: true
