name: flutter build --release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    name: Release build for ${{ matrix.target }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: web --base-href "/gptool/"
            file: gptool-web.zip
            path: .
            directory: ./build/web/
          - os: ubuntu-latest
            target: apk --target-platform android-arm64 --split-per-abi
            file: app-arm64-v8a-release.apk
            path: .
            directory: ./build/app/outputs/flutter-apk
          - os: ubuntu-latest
            target: linux
            file: gptool-linux-x64.zip
            path: .
            directory: ./build/linux/x64/release/bundle/
          - os: windows-latest
            target: windows
            file: gptool-windows.zip
            path: .
            directory: ./build/windows/runner/Release/
          - os: macos-latest
            target: macos
            file: gptool-darwin-universal.zip
            path: gptool.app
            directory: ./build/macos/Build/Products/Release
          - os: macos-latest
            target: ios --release --no-codesign
            file: gptool-ios.zip
            path: Runner.app
            directory: ./build/ios/iphoneos
    steps:
      - if: ${{ startsWith(matrix.target, 'windows') }}
        run: git config --system core.longpaths true
      - uses: actions/checkout@v3
      - if: ${{ startsWith(matrix.target, 'apk') }}
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - if: ${{ matrix.target == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
      - run: flutter build ${{ matrix.target }}

      - if: ${{ startsWith(matrix.target, 'web') }}
        name: Setup Pages
        uses: actions/configure-pages@v3
      - if: ${{ startsWith(matrix.target, 'web') }}
        name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build/web/"
      - if: ${{ startsWith(matrix.target, 'web') }}
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - if: ${{ startsWith(matrix.target, 'apk') == false }}
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: ${{ matrix.file }}
          path: ${{ matrix.path }}
          directory: ${{ matrix.directory }}
          custom: -y
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.directory }}/${{ matrix.file }}
          generate_release_notes: true
          draft: true
